// Code generated by protoc-gen-go.
// source: user-service.proto
// DO NOT EDIT!

/*
Package users is a generated protocol buffer package.

It is generated from these files:
	user-service.proto

It has these top-level messages:
	IdMessage
	User
*/
package users

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IdMessage struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *IdMessage) Reset()                    { *m = IdMessage{} }
func (m *IdMessage) String() string            { return proto.CompactTextString(m) }
func (*IdMessage) ProtoMessage()               {}
func (*IdMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IdMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type User struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Nickname  string `protobuf:"bytes,3,opt,name=nickname" json:"nickname,omitempty"`
	Bio       string `protobuf:"bytes,4,opt,name=bio" json:"bio,omitempty"`
	Location  string `protobuf:"bytes,5,opt,name=location" json:"location,omitempty"`
	Age       int32  `protobuf:"varint,6,opt,name=age" json:"age,omitempty"`
	Website   string `protobuf:"bytes,7,opt,name=website" json:"website,omitempty"`
	CreatedAt int32  `protobuf:"varint,8,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt int32  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *User) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *User) GetCreatedAt() int32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *User) GetUpdatedAt() int32 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*IdMessage)(nil), "users.IdMessage")
	proto.RegisterType((*User)(nil), "users.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	GetUserCall(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*User, error)
	CreateUserCall(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUserCall(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/users.UserService/GetUserCall", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUserCall(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/users.UserService/CreateUserCall", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	GetUserCall(context.Context, *IdMessage) (*User, error)
	CreateUserCall(context.Context, *User) (*User, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUserCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetUserCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserCall(ctx, req.(*IdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUserCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUserCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/CreateUserCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUserCall(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "users.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserCall",
			Handler:    _UserService_GetUserCall_Handler,
		},
		{
			MethodName: "CreateUserCall",
			Handler:    _UserService_CreateUserCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user-service.proto",
}

func init() { proto.RegisterFile("user-service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x91, 0xbd, 0x4a, 0xc4, 0x40,
	0x14, 0x85, 0xc9, 0xfe, 0xe7, 0x06, 0x97, 0xf5, 0xda, 0x0c, 0x51, 0x41, 0x52, 0x89, 0x60, 0x02,
	0xda, 0x09, 0x16, 0x61, 0x0b, 0xb1, 0xb0, 0x59, 0xb1, 0x96, 0x49, 0x32, 0x84, 0xc1, 0x98, 0x09,
	0x99, 0x59, 0x2d, 0xc4, 0xc6, 0x17, 0xb0, 0xf0, 0xd1, 0xec, 0xad, 0x7c, 0x10, 0x33, 0x37, 0x3f,
	0xa8, 0x45, 0xe0, 0xdc, 0xef, 0x9c, 0x39, 0x99, 0xdc, 0x00, 0x6e, 0xb5, 0xa8, 0x4f, 0x9b, 0xe7,
	0x49, 0xa6, 0x22, 0xac, 0x6a, 0x65, 0x14, 0x4e, 0x2d, 0xd3, 0xfe, 0x41, 0xae, 0x54, 0x5e, 0x88,
	0x88, 0x57, 0x32, 0xe2, 0x65, 0xa9, 0x0c, 0x37, 0x52, 0x95, 0xba, 0x0d, 0x05, 0xfb, 0xe0, 0x5e,
	0x67, 0x37, 0x42, 0x6b, 0x9e, 0x0b, 0x5c, 0xc2, 0x48, 0x66, 0xcc, 0x39, 0x72, 0x8e, 0xdd, 0x4d,
	0xa3, 0x82, 0x2f, 0x07, 0x26, 0x77, 0x4d, 0xc9, 0x7f, 0x03, 0x11, 0x26, 0x25, 0x7f, 0x14, 0x6c,
	0x44, 0x84, 0x34, 0xfa, 0xb0, 0x28, 0x65, 0xfa, 0x40, 0x7c, 0x4c, 0x7c, 0x98, 0x71, 0x05, 0xe3,
	0x44, 0x2a, 0x36, 0x21, 0x6c, 0xa5, 0x4d, 0x17, 0x2a, 0xa5, 0xab, 0xb0, 0x69, 0x9b, 0xee, 0x67,
	0x9b, 0x6e, 0x6e, 0xc3, 0x66, 0x0d, 0x9e, 0x6e, 0xac, 0x44, 0x06, 0xf3, 0x67, 0x91, 0x68, 0x69,
	0x04, 0x9b, 0x53, 0xb8, 0x1f, 0xf1, 0x10, 0x20, 0xad, 0x05, 0x37, 0x22, 0xbb, 0xe7, 0x86, 0x2d,
	0xe8, 0x88, 0xdb, 0x91, 0xd8, 0x58, 0x7b, 0x5b, 0x65, 0xbd, 0xed, 0xb6, 0x76, 0x47, 0x62, 0x73,
	0xf6, 0xee, 0x80, 0x67, 0x3f, 0xf0, 0xb6, 0x5d, 0x1c, 0xc6, 0xe0, 0x5d, 0x09, 0x63, 0xc9, 0x9a,
	0x17, 0x05, 0xae, 0x42, 0x5a, 0x61, 0x38, 0x6c, 0xc8, 0xf7, 0x3a, 0x62, 0x23, 0xc1, 0xde, 0xdb,
	0xe7, 0xf7, 0xc7, 0x68, 0x07, 0xbd, 0x88, 0x60, 0xf4, 0x22, 0xb3, 0x57, 0xbc, 0x84, 0xe5, 0x9a,
	0x5e, 0x3f, 0xb4, 0xfc, 0x3e, 0xf3, 0xb7, 0x60, 0x97, 0x0a, 0xbc, 0x60, 0xd6, 0x16, 0x5c, 0x38,
	0x27, 0xc9, 0x8c, 0x7e, 0xcb, 0xf9, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x0e, 0x7b, 0x0d,
	0xd1, 0x01, 0x00, 0x00,
}
